### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by renzifeng** [DeveloperLx/LxTabBadgePoint#1]
我已把Nav加到tabBarController，还是提示：LxTabBadgePoint：This viewController not embed in tabBarController

**Comment by DeveloperLx** [comment]
你把Nav添加到tabBarController，那就应该使用 nav.showTabBadgePoint = YES/NO; 啊。说明你对tabBarController的机制还不够理解

**Comment by renzifeng** [comment]
nav.showTabBadgePoint = YES，设置了，但是不显示，提示LxTabBadgePoint：This viewController not embed in tabBarController

**Comment by DeveloperLx** [comment]
你仔细比对下demo，我这边怎么试都是没问题的。肯定是你的用法有问题，或对tabBarController的理解不够正确

**Comment by renzifeng** [comment]
谢谢 我已经找到原因了，是我重新了Nav的一些方法导致的。

**Comment by renzifeng** [comment]
谢谢 我已经找到原因了，是我重写了Nav的一些方法导致的。

**Comment by renzifeng** [comment]
谢谢 我已经找到原因了，是我重写了Nav的一些方法导致的。
